### ISSUE TITLE
fli push fails with error "Differ error too many levels of symbolic links"

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/fli#10] opened 2016-12-06 11:53 UTC
While following examples in https://github.com/ClusterHQ/examples I encounter the following error:

```
docker@fli-vm:~$ fli push richardw-volumeset-1
Upload snapshot 0f0a9aa6-768b-401b-8c1f-e44e59ed6992 failed: Put http://ec2-35-160-189-40.us-west-2.compute.amazonaws.com:80/upload?token=98ec9168-3307-4517-927f-87f308b0acba: Differ error too many levels of symbolic links
```

The volumeset, volume and snapshots show up at www.flockerhub.clusterhq.com.

```
docker@fli-vm:~$ fli version
Version:    0.6.0
Git commit: a4c0d93
```

```
docker@fli-vm:~$ sudo cat /root/.fli/config
current: /root/.fli/mds_current
initial: /root/.fli/mds_initial
url: https://data.flockerhub.clusterhq.com
token: /root/token.txt
zpool: chq

```

```
docker@fli-vm:~$ fli search --all --full
VOLUMESET ID                         CREATOR                              CREATED         SIZE  DESCRIPTION ATTRIBUTES NAME
97244daf-0b65-4737-8a40-495c34f2888a fe59a254-bd67-4f05-a423-b99592a2cb73 Dec  6 11:18:11 29 KB -           -          My-VolumeSet
     BRANCH SNAPSHOT TIP
     -      My-Snapshot
     SNAPSHOT ID                          OWNER                                CREATOR                              CREATED         SIZE   DESCRIPTION ATTRIBUTES NAME
     8050111a-20b1-412f-aaff-1a37f3baf0aa fe59a254-bd67-4f05-a423-b99592a2cb73 fe59a254-bd67-4f05-a423-b99592a2cb73 Dec  6 11:18:37 9.5 KB -           -          My-Snapshot
     VOLUME ID                            CREATED         SIZE MOUNT POINT                                                                    NAME
     4d1dc3a1-4fa2-468d-a52e-d22323f59a14 Dec  6 11:18:17 0    /chq/97244daf-0b65-4737-8a40-495c34f2888a/4d1dc3a1-4fa2-468d-a52e-d22323f59a14 My-Volume
VOLUMESET ID                         CREATOR                              CREATED         SIZE  DESCRIPTION ATTRIBUTES                                           NAME
b5c553c1-e73b-4b2d-9751-8af4066eb57c fe59a254-bd67-4f05-a423-b99592a2cb73 Dec  6 11:34:22 29 KB foo bar baz reason=https://github.com/ClusterHQ/fli-docs/pull/85 richardw-volumeset-1
     BRANCH SNAPSHOT TIP
     -      snapshot-1
     SNAPSHOT ID                          OWNER                                CREATOR                              CREATED         SIZE   DESCRIPTION ATTRIBUTES                                           NAME
     0f0a9aa6-768b-401b-8c1f-e44e59ed6992 fe59a254-bd67-4f05-a423-b99592a2cb73 fe59a254-bd67-4f05-a423-b99592a2cb73 Dec  6 11:37:37 9.5 KB -           reason=https://github.com/ClusterHQ/fli-docs/pull/85 snapshot-1
     VOLUME ID                            CREATED         SIZE MOUNT POINT                                                                    NAME
     b48af388-1795-4561-bba8-526adeaa0eb2 Dec  6 11:35:25 0    /chq/b5c553c1-e73b-4b2d-9751-8af4066eb57c/b48af388-1795-4561-bba8-526adeaa0eb2 volume-1
```

**Comment by wallnerryan** [comment] 2016-12-06 14:08
@wallrj its worth noting that the example I think you are using is `examples/fli-docker-toolbox` and this actually runs on a Boot2Docker OS based on RancherOS that overlays Ubuntu 16.04. So Its not on our supported list, this is meant for users to try out fli not, use it permanently with this system.

**Comment by wallnerryan** [comment] 2016-12-06 14:42
was able to reproduce, this is probably due to the unsupported OS. So not sure it a valid issue

**Comment by wallnerryan** [comment] 2016-12-06 15:02
removed this from examples. closing

**Closed by wallnerryan** 2016-12-06 15:02 UTC
